### ISSUE TITLE
Extend also to SKSE plugins?

### ISSUE THREAD

**Issue by ryobg** [Ryan-rsm-McKenzie/ConsoleUtilSSE#1]
Heya, been wondering... Are you willing to add some interface for other SKSE plugins to use these 6 functions? I'm thinking to play around with some GUI for a console and l'm bit hesitant to go all that address hunting and stuff when I can call just some function of yours. 

I have downloaded your two projects, but fought some time to make them compile and changed things around. At the end though, I was able to test out the following code added to main.cpp and it works! I'm not confident how to fit it in your coding guidelines so, I just post here you will see how to better integrate it.

```c++
namespace PluginInterface
{
	void ExecuteCommand (const char* command)
	{
		Papyrus::ConsoleUtil::ExecuteCommand (nullptr, command);
	}

	std::uintptr_t GetSelectedReference ()
	{
		return (std::uintptr_t) Papyrus::ConsoleUtil::GetSelectedReference (nullptr);
	}

	void SetSelectedReference (std::uintptr_t a_reference)
	{
		Papyrus::ConsoleUtil::SetSelectedReference (nullptr, (RE::TESObjectREFR*) a_reference);
	}

	void ReadMessage (char* a_msg, std::int32_t* a_size)
	{
		auto msg = Papyrus::ConsoleUtil::ReadMessage (nullptr);
		std::copy_n (msg.data (), std::min ((int) msg.size (), *a_size), a_msg);
		*a_size = (int) msg.size ();
	}

	void PrintMessage (const char* a_message)
	{
		return Papyrus::ConsoleUtil::PrintMessage (nullptr, a_message);
	}

	std::int32_t GetVersion ()
	{
		return Papyrus::ConsoleUtil::GetVersion (nullptr);
	}
}

void MessageHandler(SKSE::MessagingInterface::Message* a_msg)
{
	switch (a_msg->type) {
	case SKSE::MessagingInterface::kDataLoaded:
		Events::Register();
		break;
	case SKSE::MessagingInterface::kPostPostLoad:
		void* ptrs[] = { &PluginInterface::ExecuteCommand, &PluginInterface::GetSelectedReference, &PluginInterface::GetSelectedReference,
			&PluginInterface::ReadMessage, &PluginInterface::PrintMessage, &PluginInterface::GetVersion };
		SKSE::GetMessagingInterface ()->Dispatch (1, &ptrs, sizeof (ptrs), nullptr);
		break;
	}
}
```

**Comment by ryobg** [comment]
Maybe two more remarks: I'm using plain types as I don't want to mess runtimes and that `1` in front would serve as API version interface.

**Comment by Ryan-rsm-McKenzie** [comment]
If you're writing an SKSE plugin, you will find it infinitely easier to just invoke the underlying functions yourself. CommonLib provides utilities for relocating version independent addresses at runtime.

**Comment by ryobg** [comment]
No, it is not a SKSE plugin, sort of. It uses SKSE only to inject itself within the SSE process and a bit of intercommunication between few DLLs (which can be easily replaced). I'm not really willing to add CommonLib as build dependency as my build/dev system is very different. 

I will have to search for another solution, I take it, this proposal is not so welcomed?

**Comment by Ryan-rsm-McKenzie** [comment]
I'm not interested in adding this interface

**Comment by ryobg** [comment]
Okay, thank you for the fast response!
